services:
  db:
    image: postgres:14.1-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password

  redis:
    image: redis:6.2-alpine
    command: redis-server
    volumes:
      - redis:/data

  chrome:
    image: blog_base
    command: bash -c "/usr/bin/true"
    ports:
      - "31337:31337"
    volumes:
      - .:/app
      - bundle:/bundle
      - node_modules:/app/node_modules
    environment:
      - BUNDLE_PATH=/bundle
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=db
      - REDIS_URL=redis://redis:6379
      - RAILS_ENV=test
      - RACK_ENV=test
    depends_on:
      - db

  selenium:
    image: selenium/standalone-chrome

volumes:
  db: {}
  bundle: {}
  node_modules: {}
  redis: {}
